### ISSUE TITLE
fails if cert target secret exists but key not set

### ISSUE THREAD

**Issue by progrium** [gliderlabs/kube-certdaemon#1]
When using an existing secret to store the cert files, it will assume if the secret exists, the key for an existing cert will exist and try to decode. Then it will fail.

**Comment by Omeryl** [comment]
I don't understand, can you elaborate @progrium?

**Comment by Omeryl** [comment]
It's assuming secrets are of type "tls" which require a certificate and private key always.

**Comment by progrium** [comment]
if the secret for a cert is `cmd-beta` and that secret exists, it will just blindly load the key `tls.crt` to check its expiration. However, if the key is not set, you get empty data so parsing fails with invalid PEM.

**Comment by Omeryl** [comment]
@progrium this program makes the assumptions that your secrets are of type `tls` and not of type `generic.` So .. those secrets always have both keys set.

**Comment by progrium** [comment]
Closing since we designed this out of relevance
